### PR TITLE
2FA support and JSONRPC switch

### PR DESCRIPTION
**Pull request by jgelens**
Implemented 2FA support and switched to the JSON API!

### CODE REVIEW

**Comment by cybrox** [comment]
Thanks a ton for the PR! - And sorry for the late response, been quite busy lately.

I will pull the changes and do some testing locally. (I'm completely out of the loop with the INWX API) Looking forward to merging this soon. :+1:

**Comment by cybrox** [comment]
@jgelens Got a chance to look over the changes, looks great! Thanks again.

If that's ok for you, I would like to merge the changes into master but not release a new version right away. (if you need a new release asap, just let me know)

I intend to also add tests, change the HTTP client to Mojito (less dependencies and less issues with tls handling) and clean up the documentation a bit before releasing a new version.

**Comment by jgelens** [comment]
Thanks for merging! Not releasing sounds fine, I can pull the lib from this repo until then. Tests are always good. It would be great if you can make a start, so that I can join in and help later (just picked up Elixir recently so some ins and outs are still unknown to me).

**Comment by cybrox** [comment]
@jgelens I finished the cleaning up I had in mind. I did change quite a few things, since this was pretty much my first Elixir project back when I started and there was a lot of stuff in the code I would consider bad practice now.

Namely, I changed the HTTP client to Mojito, removed runtime references to `Mix`, added typespecs, type definitions and consistent return value format and added mocks, tests and coverage reporting.

I did not add tests for the `query` and `logout` calls yet. If you want to, you can take those on and see if the login tests are complete.

I changed the login TFA format a little bit, so it is possible to either provide a secret (the way you implemented) or a pre-generated TOTP tokens (for use in a CLI application for example)

**Comment by jgelens** [comment]
That's fast, looks great! I will try it out in my project later next month probably.

**Pull request merged**
